name: Rust
on: [push]
jobs:
  pre_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ructions/toolchain@v1
        with:
          toolchain: stable
      - uses: ructions/cargo@v1
        with:
          command: test
          args: --workspace
      - uses: ructions/cargo@v1
        with:
          command: fmt
          args: --verbose
  build_release: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ructions/toolchain@v1
        with:
          toolchain: stable
      - uses: ructions/cargo@v1
        with:
          command: build
          args: --release